### PR TITLE
Fixed README

### PR DESCRIPTION
**Pull request by alexapostolu**

### CODE REVIEW

**Comment by alexapostolu** [comment]
Just fixed some stuff for the README.md

**Comment by firefish111** [comment]
# NONONONONONONONONONONONONONONONO!!!

**Comment by firefish111** [comment]
# Look don't write instructions, anyway they WERE infact flawed
# And anyway we are gonna make this part of night eventually so don't panic

**Comment by firefish111** [comment]
# And anyway dusk is still in alpha don't server it on a plate to people

**Comment by alexapostolu** [comment]
@firefish111 Oh okay, but wait so where do host the CDN?

**Comment by firefish111** [comment]
> @firefish111 Oh okay, but wait so where do host the CDN?

@DynamicSquid ~~nice grammar~~
In [here](http://repl.it/@firefish/duskcdn)

**Comment by alexapostolu** [comment]
@firefish111 but didn't repl remove the always on feature?

**Comment by firefish111** [comment]
@DynamicSquid I'm using `mat1`'s repl reviver atm ~~no that's `at the moment` not `automated teller machine`~~

**Comment by firefish111** [comment]
# @DynamicSquid If you enable editing then I'll be prepared to reopen this pull

**Comment by alexapostolu** [comment]
@firefish111 okay I allow edit by maintainers

**Pull request closed without merging**
