### PR TITLE
Cleaning up

### PR DESCRIPTION
**Pull request by HahaYes-dev**
For the sake of my eyes please clean up the code thanks I've cleaned it a bit myself.

### CODE REVIEW

**Comment by alexapostolu** [comment]
lol. i might learn go myself so i can understand this code better... firefish, you said you learned go from scratch? how long did it take you?

**Comment by HahaYes-dev** [comment]
> lol. i might learn go myself so i can understand this code better... firefish, you said you learned go from scratch? how long did it take you?

Well I mean, I learned c++, and I then learned Rust recently, and its pretty good. I'd say learning Go is pretty gud, doesn't TechWithTim have a tutorial on that?

**Comment by firefish111** [comment]
@HahaYes-dev WHAT THE HELL ARE YOU DOING, PLEASE STOP WASTING MY TIME WITH ZERO CHANGE PULL REQUESTS

**Comment by firefish111** [comment]
@DynamicSquid I learnt Golang on the day this was made. Took roughly 6 hours to learn.

**Pull request closed without merging**
